name: Account-service build and push to docker-hub workflow

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout account-service project
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build Docker image and push to docker-hub
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: finance/account-service:latest
          push: true
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"