name: Account-service CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout account-service project 
        uses: actions/checkout@v3
      
      - name: set-up jdk 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
          
      - name: run unit-tests
        run: ./mvnw test
      
